name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
            file_suffix: linux-amd64
          - goarch: arm64
            goos: linux
            file_suffix: linux-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go mod download
          go build -ldflags="-s -w" -o probe-${{ matrix.file_suffix }} main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: probe-${{ matrix.file_suffix }}
          path: probe-${{ matrix.file_suffix }}
